In [ ]:
import numpy as np
import pandas as pd

In [ ]:
temp_df = pd.read_csv('IMDB Dataset.csv')

In [ ]:
df = temp_df.iloc[:10000]

In [ ]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [ ]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [ ]:
df.duplicated().sum()

17

In [ ]:
df.drop_duplicates(inplace=True)

/tmp/ipython-input-9-3006716147.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [ ]:
df.duplicated().sum()

0

In [ ]:
import re

In [ ]:
def removehtml(data):
  p = re.compile(r"<.*?>")
  return p.sub(r"",data)

In [ ]:
#removing html tags
df['review'] = df['review'].apply(removehtml)

/tmp/ipython-input-13-3173683731.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(removehtml)


In [ ]:
df['review']

0       One of the other reviewers has mentioned that ...
1       A wonderful little production. The filming tec...
2       I thought this was a wonderful way to spend ti...
3       Basically there's a family where a little boy ...
4       Petter Mattei's "Love in the Time of Money" is...
                              ...                        
9995    Fun, entertaining movie about WWII German spy ...
9996    Give me a break. How can anyone say that this ...
9997    This movie is a bad movie. But after watching ...
9998    This is a movie that was probably made to ente...
9999    Smashing film about film-making. Shows the int...
Name: review, Length: 9983, dtype: object

In [ ]:
#lowering the text
def lower(data):
  return data.lower()

df['review'] = df['review'].apply(lower)

/tmp/ipython-input-15-2335259748.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lower)


In [ ]:
#removing stop words

import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from nltk.corpus import stopwords
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [ ]:
def removestopwords(data):
    stop_words = set(stopwords.words('english'))  # Load once
    new_text = [word for word in data.split() if word not in stop_words]
    return " ".join(new_text)

In [ ]:
df['review'] = df['review'].apply(removestopwords)

/tmp/ipython-input-19-2359601681.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(removestopwords)


In [ ]:
df

review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production. filming technique...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. anyone say "good hockey movie"? kn...  negative
9997  movie bad movie. watching endless series bad h...  negative
9998  movie probably made entertain middle school, e...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [ ]:
X = df.iloc[:, 0: 1]
y = df['sentiment']

In [ ]:
X

review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [ ]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...   
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [ ]:
#lable encoding for the output
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [ ]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
X_train.shape

(7986, 1)

In [ ]:
#applying bag of words

from sklearn.feature_extraction. text import CountVectorizer

In [ ]:
cv = CountVectorizer()

In [ ]:
X_train_cv = cv.fit_transform(X_train['review']).toarray()
X_test_cv = cv.transform(X_test['review']).toarray()

In [ ]:
X_train_cv.shape

(7986, 48282)

In [ ]:
#applying randomforest classifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf = RandomForestClassifier()

rf.fit(X_train_cv, y_train)

y_pred = rf.predict(X_test_cv)

accuracy_score(y_test, y_pred)

0.8582874311467201

In [ ]:
! pip install gensim

In [ ]:
import gensim

In [ ]:
from gensim.utils import simple_preprocess

In [ ]:
import re
import gensim
from gensim.utils import simple_preprocess
from gensim.models import Word2Vec

# Tokenizer
def tokenizer(text):
    return re.findall(r'\b\w+\b', text.lower())

# Build the corpus
story = []
for doc in df['review']:
    tokens = tokenizer(doc)  # list of tokens
    story.append(tokens)     # each review is one list of tokens

# Train Word2Vec
model = Word2Vec(window=10, min_count=2)
model.build_vocab(story)  # this works now because 'story' is a list of list of tokens
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)


(6013901, 6399340)

In [ ]:
len(model.wv.index_to_key)

32314

In [ ]:
def document_vecotr(doc):
  #remove out of vocabulary words
  doc = [word for word in doc.split() if word in model.wv.index_to_key ]
  return np.mean(model.wv[doc], axis = 0)


In [ ]:
document_vecotr(df['review'].values[0])

array([-2.12002143e-01,  2.82264501e-01, -1.15984846e-02,  9.51156989e-02,
        3.18581867e-03, -3.82878751e-01,  3.65872204e-01,  7.06614733e-01,
       -1.22931294e-01, -1.60100996e-01, -4.57732566e-02, -8.34676206e-01,
        2.28422042e-03, -4.38092723e-02,  1.79608241e-01, -3.09896767e-01,
       -2.46634483e-02, -4.00785565e-01, -1.30431458e-01, -7.70292699e-01,
        3.73661309e-01,  3.24964583e-01,  3.52426589e-01, -8.05875286e-02,
        5.35247810e-02,  1.40688509e-01, -4.64482039e-01, -4.40374255e-01,
       -4.46616858e-01, -1.48518151e-02,  3.82449180e-01, -5.11091426e-02,
        1.69729516e-01, -3.18753392e-01, -1.85483739e-01,  5.05342126e-01,
        3.20013702e-01, -2.96924226e-02, -1.33359224e-01, -5.56376457e-01,
        2.15890557e-01, -2.79544592e-01, -1.59871846e-01, -5.82759492e-02,
        3.46749157e-01, -2.64726043e-01, -2.73585677e-01, -2.61737853e-01,
        3.76374811e-01,  1.93432897e-01, -8.60155895e-02, -3.43490630e-01,
       -2.01105997e-01, -

In [ ]:
from tqdm import tqdm

In [ ]:
X = []
for doc in tqdm(df['review'].values):
  X.append(document_vecotr(doc))

100%|██████████| 9983/9983 [05:27<00:00, 30.47it/s]


In [ ]:
X = np.array(X)

In [ ]:
X[0]

array([-2.12002143e-01,  2.82264501e-01, -1.15984846e-02,  9.51156989e-02,
        3.18581867e-03, -3.82878751e-01,  3.65872204e-01,  7.06614733e-01,
       -1.22931294e-01, -1.60100996e-01, -4.57732566e-02, -8.34676206e-01,
        2.28422042e-03, -4.38092723e-02,  1.79608241e-01, -3.09896767e-01,
       -2.46634483e-02, -4.00785565e-01, -1.30431458e-01, -7.70292699e-01,
        3.73661309e-01,  3.24964583e-01,  3.52426589e-01, -8.05875286e-02,
        5.35247810e-02,  1.40688509e-01, -4.64482039e-01, -4.40374255e-01,
       -4.46616858e-01, -1.48518151e-02,  3.82449180e-01, -5.11091426e-02,
        1.69729516e-01, -3.18753392e-01, -1.85483739e-01,  5.05342126e-01,
        3.20013702e-01, -2.96924226e-02, -1.33359224e-01, -5.56376457e-01,
        2.15890557e-01, -2.79544592e-01, -1.59871846e-01, -5.82759492e-02,
        3.46749157e-01, -2.64726043e-01, -2.73585677e-01, -2.61737853e-01,
        3.76374811e-01,  1.93432897e-01, -8.60155895e-02, -3.43490630e-01,
       -2.01105997e-01, -

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(df['sentiment'])

In [ ]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


In [ ]:
mnb = RandomForestClassifier()

In [ ]:
mnb.fit(X_train, y_train)


RandomForestClassifier()

In [ ]:
y_pred = mnb.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7946920380570857

In [ ]:
import pickle

# Save model
with open('mnb.pkl', 'wb') as f:
    pickle.dump(rf, f)

# Save vectorizer
with open('vectorizer.pkl', 'wb') as f:
    pickle.dump(cv, f)

